import type { Metadata } from "next";
import { Inter, Volkhov, Mulish, Montserrat, Comforter_Brush } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-volkhov",
  display: "swap",
});
const mulish = Mulish({
  subsets: ["latin", "vietnamese"],
  variable: "--font-mulish",
  display: "swap",
});
const montserrat = Montserrat({
  subsets: ["latin", "vietnamese"],
  variable: "--font-montserrat",
  display: "swap",
});
const comforterBrush = Comforter_Brush({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-comforter-brush",
  display: "swap",
});

import type { Viewport } from "next";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
export const metadata: Metadata = {
  metadataBase: new URL("https://www.canthaitoan.com/"),
  title: "Cân Thái Toàn",
  description: "Generated by create next app",
  openGraph: {
    images: ["/logo.jpg"],
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://canthaitoan-be.click" />
        <link rel="dns-prefetch" href="https://canthaitoan-be.click" />
      </head>
      <body className={`${inter.variable} ${volkhov.variable} ${mulish.variable} ${montserrat.variable} ${comforterBrush.variable}`}>
        <Navbar />
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        <Footer />
        <div className="bg-gradient-to-b from-sky-700 to-sky-600 h-6"></div>
      </body>
    </html>
  );
}
