// GENERATED by scripts/optimize-images.mjs — do not edit.
// Run `npm run optimize:images` (or `npm run build`) to regenerate.

export type StaticImage = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const staticImages = {
  "brand/Mettler_Toledo": {
    "src": "/img/brand/Mettler_Toledo-960.webp",
    "srcSet": "/img/brand/Mettler_Toledo-160.webp 160w, /img/brand/Mettler_Toledo-320.webp 320w, /img/brand/Mettler_Toledo-480.webp 480w, /img/brand/Mettler_Toledo-720.webp 720w, /img/brand/Mettler_Toledo-960.webp 960w",
    "width": 960,
    "height": 597,
    "blurDataURL": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4WAoAAAAQAAAADwAACQAAQUxQSGYAAAABcFvbtqLc8RkgcvmS4u7uxHQAEZG7dEFKAxQ6WkJEkE3a0DqVPgIAUoxYkiTJoBeiA2LHqg4EU3c3IhYAAoQ01/971mQrW7w7dr/z6frlhdVns70kACzqqeWMknRtOOrosI/2BwBWUDggSgAAALABAJ0BKhAACgADgFoljAJ0AKhZ8AAA/uyOmkw78DvrEshlZNrQxt5CSE/oq8NI3Ltnctay/lJLHhyfkTDBs0B5hk7R3TofwAAA"
  },
  "brand/cas": {
    "src": "/img/brand/cas-407.webp",
    "srcSet": "/img/brand/cas-160.webp 160w, /img/brand/cas-320.webp 320w, /img/brand/cas-407.webp 407w",
    "width": 407,
    "height": 124,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAUAA4BaJZgCdAEfv20X0AD+CR6tlqbVBbwpz0nW1k2Xmm/Aq3Yg51lpXoAVhYElcTVEPemEN4mZx+87VshtrsyfqvgA"
  },
  "brand/excell": {
    "src": "/img/brand/excell-600.webp",
    "srcSet": "/img/brand/excell-160.webp 160w, /img/brand/excell-320.webp 320w, /img/brand/excell-480.webp 480w, /img/brand/excell-600.webp 600w",
    "width": 600,
    "height": 400,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoQAAsAA4BaJZwAAlvCojAA/vi6cGulRnLeGJW7lmK1lfdXc5E8wg9zuGf4EisO/Ef/4RgAAAA="
  },
  "brand/ohaus": {
    "src": "/img/brand/ohaus-650.webp",
    "srcSet": "/img/brand/ohaus-160.webp 160w, /img/brand/ohaus-320.webp 320w, /img/brand/ohaus-480.webp 480w, /img/brand/ohaus-650.webp 650w",
    "width": 650,
    "height": 650,
    "blurDataURL": "data:image/webp;base64,UklGRjIBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSLYAAAABgKtt//nl87eZzcnW1GbXVgdg1+aa7Jps23UCdpPtza7P8P3hFCJiAoD9ziN5ftKUFsAhrhHxpbTtFxHzaKbdV5FcpvhKNjpAyjFi30+ygdSxwAewgjqk3ucLCwHA5ofqw43bvQAAhUj5E8NrQWKQ4ilUdx4pSohF27h7pJIUj5Z7awsmyUIAuwg9VzMDX2dbhYu1v50VXGPnXn89/je7Tiwt5wTA4HlaR2ZBVmV8W19SdS6wB1ZQOCBWAAAAcAIAnQEqEAAQAAOAWiWwAnQ4gDeAAXI3rjDagAD+2VxYbEh+hAAdy3qL907Jpew8+FofM4VXBGGjX/5cHhoilU39m6WeSiNv6iln7FtKZgW56tQEAAA="
  },
  "brand/vibra": {
    "src": "/img/brand/vibra-500.webp",
    "srcSet": "/img/brand/vibra-160.webp 160w, /img/brand/vibra-320.webp 320w, /img/brand/vibra-480.webp 480w, /img/brand/vibra-500.webp 500w",
    "width": 500,
    "height": 500,
    "blurDataURL": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSF4AAAABcFvbtqK8cQknHpwKIHJ3dyezzF0jK4DQqyBzst8BRBQ0BUREguT9K7a6CW8ji1Fqyfe9IvuT5y8V1LyeOw/zbo9D9SOsfUj7v81Qg/6qgTRAwJ5wG2I6fZCOGUHyVlA4IDwAAADQAQCdASoQABAAA4BaJZQCdH8G6ABEAAD+8LeE7uAIzTDrVTEnBjUIy3MbB0PsjF7b0TFWuzIKGTJ4AAA="
  },
  "carousel/ACH3": {
    "src": "/img/carousel/ACH3-652.webp",
    "srcSet": "/img/carousel/ACH3-160.webp 160w, /img/carousel/ACH3-320.webp 320w, /img/carousel/ACH3-480.webp 480w, /img/carousel/ACH3-652.webp 652w",
    "width": 652,
    "height": 652,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQABAAA4BaJaQAAuTobvNfAAD++LlvjNK0wJD390ui8f0Gh/U2BqtjA+omI17tXMNIjneWr18Bef22X1/ILVF18JekOZwAAAA="
  },
  "carousel/CB": {
    "src": "/img/carousel/CB-350.webp",
    "srcSet": "/img/carousel/CB-160.webp 160w, /img/carousel/CB-320.webp 320w, /img/carousel/CB-350.webp 350w",
    "width": 350,
    "height": 350,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQABAAA4BaJaQAAlvu2AwAAP74umiIWcR0PuNuZ8BhR6yOj8EpQcaVy3PV2a3HpU2/wAAA"
  },
  "carousel/HT": {
    "src": "/img/carousel/HT-663.webp",
    "srcSet": "/img/carousel/HT-160.webp 160w, /img/carousel/HT-320.webp 320w, /img/carousel/HT-480.webp 480w, /img/carousel/HT-663.webp 663w",
    "width": 663,
    "height": 800,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABMAPu1iqk2ppaQiMAgBMB2JZwDLLB0+co8s/SyXnHYcAP7yKd2eceLPGjV0ANKbU5se/vuZJ5A9ns36Knge00nJMN55zHOz7pthuNiQ/bm4bqOk8AAA"
  },
  "carousel/LN": {
    "src": "/img/carousel/LN-814.webp",
    "srcSet": "/img/carousel/LN-160.webp 160w, /img/carousel/LN-320.webp 320w, /img/carousel/LN-480.webp 480w, /img/carousel/LN-720.webp 720w, /img/carousel/LN-814.webp 814w",
    "width": 814,
    "height": 542,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAsAA4BaJZwAAuOB3xgAAP72F/WyKb2s6pjP5ycxgs4T5AcBxPqkW81yvHQ5cPNtgAAA"
  },
  "carousel/PX": {
    "src": "/img/carousel/PX-960.webp",
    "srcSet": "/img/carousel/PX-160.webp 160w, /img/carousel/PX-320.webp 320w, /img/carousel/PX-480.webp 480w, /img/carousel/PX-720.webp 720w, /img/carousel/PX-960.webp 960w",
    "width": 960,
    "height": 960,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQABAAA4BaJaQAAuQvYWZu6aQA/vgQBzvL0z3bLymgy+5QzhYFVI6KDFOzwChPZWPpIjNIfev9xlVfpkQAAA=="
  },
  "logo": {
    "src": "/img/logo-960.webp",
    "srcSet": "/img/logo-160.webp 160w, /img/logo-320.webp 320w, /img/logo-480.webp 480w, /img/logo-720.webp 720w, /img/logo-960.webp 960w",
    "width": 960,
    "height": 832,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwAgCdASoQAA4AA4BaJbACdEf/i14bbJ0Cl7TgAP74umkhgCnWxSvb8VdNb1vjWsLGqCMzP0FaWyQIMhBJ2WwplHcNiKUU/6NYcLDmec1CRkftNpC5f+Rv+t4L+uRcQus+rwXkbsCnAD4H3XG03e0SFYLgAA=="
  },
  "sample/can1": {
    "src": "/img/sample/can1-540.webp",
    "srcSet": "/img/sample/can1-160.webp 160w, /img/sample/can1-320.webp 320w, /img/sample/can1-480.webp 480w, /img/sample/can1-540.webp 540w",
    "width": 540,
    "height": 450,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAA0AA4BaJZQAAxYGlA7QqAAA/t+zNU3cM6klVHkwMP199uJWzh7zJk7bE71u9/gVsilCXR6OT1Wf3WojPtALLHAtwAxlS06uY15wkN3HF0AA"
  },
  "sample/can10": {
    "src": "/img/sample/can10-350.webp",
    "srcSet": "/img/sample/can10-160.webp 160w, /img/sample/can10-320.webp 320w, /img/sample/can10-350.webp 350w",
    "width": 350,
    "height": 350,
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoQABAAA4BaJaQAAlvsJlgA/vi6W5n36uY+SSr7glgNH9YtzIUlN1SlS2c5/WfAt3yIAA=="
  },
  "sample/can11": {
    "src": "/img/sample/can11-960.webp",
    "srcSet": "/img/sample/can11-160.webp 160w, /img/sample/can11-320.webp 320w, /img/sample/can11-480.webp 480w, /img/sample/can11-720.webp 720w, /img/sample/can11-960.webp 960w",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoQABUAPu1yrU+pp6QiMAgBMB2JYwAATvoJZa+RUMTfFAAA/vOCyvSAoNyk04WizuhGhb16qtf1/u7A0vk2giF/atZ7o01ZGIU2M6TU4/jybAVTb+dhn3asyp/kjV/6n0bHFjQXMIpAeEAA"
  },
  "sample/can12": {
    "src": "/img/sample/can12-500.webp",
    "srcSet": "/img/sample/can12-160.webp 160w, /img/sample/can12-320.webp 320w, /img/sample/can12-480.webp 480w, /img/sample/can12-500.webp 500w",
    "width": 500,
    "height": 500,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQABAAA4BaJZQAAtp3gItI8AD++LL/p6nqP66r/B+bFGpPo6/8yAe74O9LyRJgdj7B+qYU8SdjlxAWL3ux0ApJGKZA5JA3EAA="
  },
  "sample/can2": {
    "src": "/img/sample/can2-960.webp",
    "srcSet": "/img/sample/can2-160.webp 160w, /img/sample/can2-320.webp 320w, /img/sample/can2-480.webp 480w, /img/sample/can2-720.webp 720w, /img/sample/can2-960.webp 960w",
    "width": 960,
    "height": 720,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAwAA4BaJaQAAuQmk6GjAAD+9N49aHuefxBmYrQ/asasfti532cAEi4k9I4A"
  },
  "sample/can3": {
    "src": "/img/sample/can3-800.webp",
    "srcSet": "/img/sample/can3-160.webp 160w, /img/sample/can3-320.webp 320w, /img/sample/can3-480.webp 480w, /img/sample/can3-720.webp 720w, /img/sample/can3-800.webp 800w",
    "width": 800,
    "height": 800,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQABAAA4BaJZwAD5VuytQR1lAA/vi57564BaCVY31TDXC2NnENIBzbIz2+Ih2s7GNghebbLffoWxfGtIEV1uCW/TnnoksgAUkv3ZKblJMfz9olfRyyAAAA"
  },
  "sample/can4": {
    "src": "/img/sample/can4-540.webp",
    "srcSet": "/img/sample/can4-160.webp 160w, /img/sample/can4-320.webp 320w, /img/sample/can4-480.webp 480w, /img/sample/can4-540.webp 540w",
    "width": 540,
    "height": 450,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAA0AA4BaJaQAAveBEExxuvgAAP74GX3QSOYsd19qDn6gB2fZ2+XfXqjtk1OXbN969mocr7ZA++Wv2l5okAAA"
  },
  "sample/can5": {
    "src": "/img/sample/can5-350.webp",
    "srcSet": "/img/sample/can5-160.webp 160w, /img/sample/can5-320.webp 320w, /img/sample/can5-350.webp 350w",
    "width": 350,
    "height": 350,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQABAAA4BaJQBdj+ADA2YM8DcuaAD++Lmoau6/Cn6ER+0GK2FAcRrzjKujX96ZHhtWHoPkxwQxT1mpuEcFHpgrDesAcyfHeWRP0gAA"
  },
  "sample/can6": {
    "src": "/img/sample/can6-337.webp",
    "srcSet": "/img/sample/can6-160.webp 160w, /img/sample/can6-320.webp 320w, /img/sample/can6-337.webp 337w",
    "width": 337,
    "height": 523,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoQABkAPu1iqk2ppaQiMAgBMB2JaQABHvABDBGDbBtbAAD++y3UOX+dVU0OjDUqLyB/CorzCg2jIXU1tOCyVBSnyCxqNLsRHp+SX1wITnvQAAAA"
  },
  "sample/can7": {
    "src": "/img/sample/can7-608.webp",
    "srcSet": "/img/sample/can7-160.webp 160w, /img/sample/can7-320.webp 320w, /img/sample/can7-480.webp 480w, /img/sample/can7-608.webp 608w",
    "width": 608,
    "height": 608,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQABAAA4BaJZwAD4uwhQZkpd7QUAD++LoBdOpDOkzLV/PQF0vUiLAyzlrJ5Hw46wRjEDsiQaJwGiylLA8+KLipmstAGp3zB7BtXOoQAAA="
  },
  "sample/can8": {
    "src": "/img/sample/can8-960.webp",
    "srcSet": "/img/sample/can8-160.webp 160w, /img/sample/can8-320.webp 320w, /img/sample/can8-480.webp 480w, /img/sample/can8-720.webp 720w, /img/sample/can8-960.webp 960w",
    "width": 960,
    "height": 1443,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABgAPu1mqk2ppaQiMAgBMB2JZQAAW+uWoDpeSfx2gXCQEFAA/u++HOB/Yw1Me5SsBU5/ooPTfzCgd/BoJCfPKgUNfoLzUAGTRKpCv8SOfQoe9te97E7R3Gqi51ZH56j8GnfdXpZ0l+MQAAkfAAAA"
  },
  "sample/can9": {
    "src": "/img/sample/can9-652.webp",
    "srcSet": "/img/sample/can9-160.webp 160w, /img/sample/can9-320.webp 320w, /img/sample/can9-480.webp 480w, /img/sample/can9-652.webp 652w",
    "width": 652,
    "height": 434,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAsAA4BaJaQAD5FHyDbjYAD+9hPgM7ol2M8/YF75O9RuvHEf7uF9YihwsKRd+fNHgLsYAbhK6fZzC6k36CLNsLDwlOaByecJjQEY0Te83KQAAAA="
  }
} as const;

export type StaticImageKey = keyof typeof staticImages;
