// Pre-optimizes local raster assets once, at build time, so the app never
// touches the Next.js runtime image optimizer for them.
//
// Reads src/asset/**, writes downscaled WebP variants to public/img/**, and
// generates src/asset/staticImages.ts (a manifest with src/srcSet/dimensions/
// blur placeholder). Components render these through <StaticImg> as a plain
// <img srcSet> — a cache-forever static file, zero server CPU.
//
// Run: node scripts/optimize-images.mjs   (wired as `prebuild` in package.json)

import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const SRC_DIR = path.join(root, "src/asset");
const OUT_DIR = path.join(root, "public/img");
const MANIFEST = path.join(root, "src/asset/staticImages.ts");

// Only these subfolders/files are referenced through the manifest. Everything
// else in src/asset (unused files, editor-only icons) is left alone.
const INCLUDE = [/^sample\//, /^carousel\//, /^brand\//, /^logo\.(jpg|jpeg|png)$/i];
const EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);

// Widths to emit. Only those <= the source width are produced, plus the source
// width itself as a ceiling. Covers 1x/2x for every place these assets render
// (brand logo ~120px, grid cell ~300px, carousel ~400px).
const WIDTHS = [160, 320, 480, 720, 960];
const QUALITY = 72;

async function walk(dir, base = "") {
  const out = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const rel = path.join(base, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(path.join(dir, entry.name), rel)));
    else if (EXT.has(path.extname(entry.name).toLowerCase())) out.push(rel);
  }
  return out;
}

function keyFor(rel) {
  return rel.replace(/\\/g, "/").replace(/\.[^.]+$/, "");
}

async function main() {
  const all = await walk(SRC_DIR);
  const files = all.filter((rel) => INCLUDE.some((re) => re.test(rel.replace(/\\/g, "/"))));

  await fs.rm(OUT_DIR, { recursive: true, force: true });
  await fs.mkdir(OUT_DIR, { recursive: true });

  const manifest = {};
  let savedBytes = 0;

  for (const rel of files.sort()) {
    const abs = path.join(SRC_DIR, rel);
    const key = keyFor(rel);
    const buf = await fs.readFile(abs);
    const image = sharp(buf, { failOn: "none" });
    const meta = await image.metadata();
    const srcW = meta.width ?? Math.max(...WIDTHS);
    const srcH = meta.height ?? srcW;

    const targets = [...new Set([...WIDTHS.filter((w) => w < srcW), Math.min(srcW, Math.max(...WIDTHS))])]
      .filter((w) => w > 0)
      .sort((a, b) => a - b);

    const outSubdir = path.join(OUT_DIR, path.dirname(key));
    await fs.mkdir(outSubdir, { recursive: true });

    const sources = [];
    for (const w of targets) {
      const data = await sharp(buf, { failOn: "none" })
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: QUALITY })
        .toBuffer();
      const file = `${path.basename(key)}-${w}.webp`;
      await fs.writeFile(path.join(outSubdir, file), data);
      sources.push({ url: `/img/${path.dirname(key)}/${file}`.replace("/./", "/"), w, bytes: data.length });
    }

    const largest = sources[sources.length - 1];
    const blur = await sharp(buf, { failOn: "none" })
      .resize({ width: 16 })
      .webp({ quality: 40 })
      .toBuffer();

    const renderedH = Math.round((largest.w / srcW) * srcH);
    manifest[key] = {
      src: largest.url,
      srcSet: sources.map((s) => `${s.url} ${s.w}w`).join(", "),
      width: largest.w,
      height: renderedH,
      blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    };

    savedBytes += buf.length - sources.reduce((n, s) => n + s.bytes, 0);
    console.log(`  ${key.padEnd(24)} ${(buf.length / 1024).toFixed(0).padStart(4)}KB -> ${(largest.bytes / 1024).toFixed(0)}KB  (${sources.length} variants)`);
  }

  const body =
    `// GENERATED by scripts/optimize-images.mjs — do not edit.\n` +
    `// Run \`npm run optimize:images\` (or \`npm run build\`) to regenerate.\n\n` +
    `export type StaticImage = {\n` +
    `  src: string;\n  srcSet: string;\n  width: number;\n  height: number;\n  blurDataURL: string;\n};\n\n` +
    `export const staticImages = ${JSON.stringify(manifest, null, 2)} as const;\n\n` +
    `export type StaticImageKey = keyof typeof staticImages;\n`;
  await fs.writeFile(MANIFEST, body);

  const hash = createHash("sha1").update(JSON.stringify(manifest)).digest("hex").slice(0, 8);
  console.log(`\n${files.length} assets -> public/img  |  ~${(savedBytes / 1024 / 1024).toFixed(2)}MB saved  |  manifest ${hash}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
